---
title: "Sales Report"
author: "Alexei Domorev"
date: "`r Sys.Date()`"
# always_allow_html: true
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    code_folding: none # hide
    df_print: paged
    highlight: tango
    number_sections: yes
    theme: flatly
    toc: yes
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE, # hides code chunks
    message = FALSE, # hides messages about loading libraries, etc.
    warning = FALSE, # hides warnings
    out.width = '96%', # specifies the width of the figures
    out.height = '96%',
    dpi = 300,
    fig.align = 'center'
    ) 
```

```{r libraries}
library(tidyverse)
library(lubridate)
library(tidyquant)
library(plotly)
```

```{r scripts}
source('../00_scripts/plot_sales.R')
```

```{r data}
bike_orderlines_tbl <- read_rds('../00_data/bike_sales/data_wrangled/bike_orderlines.rds')
```

```{r parameters}
interactive <- FALSE # FALSE for PDF
```


# Total Sales Charts {.tabset .tabset-fade .tabset-pills}
## Quarterly Sales Trends

```{r total-sales-charts-quarter}
plot_total_sales(unit = 'quarter', 
                 interactive = interactive)
```
## Monthly Sales Trends

```{r total-sales-charts-month}
plot_total_sales(unit = 'month', 
                 interactive = interactive)
```
## Weekly Sales Trends

```{r total-sales-charts-week}
plot_total_sales(unit = "week", 
                 date_format = "%Y-%m-%d", 
                 interactive = interactive)
```

# Category Sales Charts {.tabset .tabset-fasde .tabset-pills}

## Road {.tabset .tabset-fade}

### Quarterly

```{r, out.height="1200px"}
plot_categories(category_1 = "Road",
                unit = "quarter", 
                ncol = 1, 
                interactive = interactive)
```



### Monthly 

```{r, out.height="1200px"}
plot_categories(category_1 = "Road", 
                unit = "month", 
                ncol = 1,
                interactive = interactive)
```

### Weekly

```{r, out.height="1200px"}
plot_categories(category_1 = "Road", 
                unit = "week", 
                ncol = 1, 
                date_format = "%Y-%m-%d",
                interactive = interactive)
```

## Mountain {.tabset .tabset-fade}

### Quarterly

```{r, out.height="1200px"}
plot_categories(category_1 = "Mountain", 
                unit = "quarter", 
                ncol = 1, 
                interactive = interactive)
```



### Monthly 

```{r, out.height="1200px"}
plot_categories(category_1 = "Mountain",
                unit = "month", 
                ncol = 1, 
                interactive = interactive)
```

### Weekly

```{r, out.height="1200px"}
plot_categories(category_1 = "Mountain",
                unit = "week", 
                ncol = 1, 
                date_format = "%Y-%m-%d", 
                interactive = interactive)
```

